# Generated by Django 3.0.3 on 2020-02-24 15:47

import chemreg.compound.utils
import chemreg.compound.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cid', models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, unique=True, validators=[chemreg.compound.validators.validate_cid_prefix, chemreg.compound.validators.validate_cid_regex, chemreg.compound.validators.validate_cid_checksum])),
                ('structure', models.TextField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compound.basecompound_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
