# Generated by Django 3.0.3 on 2020-11-04 20:37

import chemreg.common.utils
import chemreg.common.validators
import chemreg.compound.models
import chemreg.compound.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fwd_create_illdefined_querystructuretype(apps, schema_editor):
    QueryStructureType = apps.get_model("compound", "QueryStructureType")
    db_alias = schema_editor.connection.alias
    QueryStructureType.objects.using(db_alias).create(
        name="ill-defined",
        label="Ill defined",
        short_description="Ill defined",
        long_description="Ill defined",
    )


def rev_create_illdefined_querystructuretype(apps, schema_editor):
    QueryStructureType = apps.get_model("compound", "QueryStructureType")
    db_alias = schema_editor.connection.alias
    QueryStructureType.objects.using(db_alias).filter(name="ill-defined").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompound',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('structure', models.TextField()),
                ('qc_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(default=chemreg.common.utils.get_current_user_pk, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basecompound_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compound.basecompound_set+', to='contenttypes.ContentType')),
                ('replaced_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='compound.BaseCompound')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basecompound_updated_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DefinedCompound',
            fields=[
                ('basecompound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compound.BaseCompound')),
                ('inchikey', models.CharField(max_length=29, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compound.basecompound',),
        ),
        migrations.CreateModel(
            name='QueryStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=49, unique=True)),
                ('label', models.CharField(max_length=99, unique=True)),
                ('short_description', models.CharField(max_length=499)),
                ('long_description', models.TextField()),
                ('deprecated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=chemreg.common.utils.get_current_user_pk, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='querystructuretype_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='querystructuretype_updated_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.RunPython(
            fwd_create_illdefined_querystructuretype,
            rev_create_illdefined_querystructuretype,
        ),
        migrations.CreateModel(
            name='IllDefinedCompound',
            fields=[
                ('basecompound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compound.BaseCompound')),
                ('query_structure_type', models.ForeignKey(default=chemreg.compound.models.get_illdefined_qst, on_delete=django.db.models.deletion.PROTECT, to='compound.QueryStructureType', validators=[chemreg.common.validators.validate_deprecated])),
            ],
            options={
                'verbose_name': 'ill-defined compound',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compound.basecompound',),
        ),
    ]
