# Generated by Django 3.0.3 on 2020-06-08 20:45

import chemreg.compound.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecompound',
            options={'base_manager_name': 'objects', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='definedcompound',
            options={'base_manager_name': 'objects', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='illdefinedcompound',
            options={'base_manager_name': 'objects', 'ordering': ['pk'], 'verbose_name': 'ill-defined compound'},
        ),
        migrations.AlterModelOptions(
            name='querystructuretype',
            options={'base_manager_name': 'objects', 'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='basecompound',
            name='qc_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='basecompound',
            name='replaced_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='compound.BaseCompound'),
        ),
        migrations.AddField(
            model_name='querystructuretype',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basecompound',
            name='cid',
            field=models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='definedcompound',
            name='inchikey',
            field=models.CharField(max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='querystructuretype',
            name='label',
            field=models.CharField(max_length=99, unique=True),
        ),
        migrations.AlterField(
            model_name='querystructuretype',
            name='long_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='querystructuretype',
            name='name',
            field=models.SlugField(max_length=49, unique=True),
        ),
        migrations.AlterField(
            model_name='querystructuretype',
            name='short_description',
            field=models.CharField(max_length=499),
        ),
    ]
