# Generated by Django 3.0.3 on 2020-05-27 19:11

import chemreg.compound.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompound',
            name='cid',
            field=models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='definedcompound',
            name='inchikey',
            field=models.CharField(max_length=29, null=True),
        ),
    ]
