# Generated by Django 3.0.3 on 2020-02-24 21:41

import chemreg.compound.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0001_basecompound'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedCompound',
            fields=[
                ('basecompound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compound.BaseCompound')),
                ('inchikey', models.CharField(max_length=29, validators=[chemreg.compound.validators.validate_inchikey_regex])),
            ],
            options={
                'abstract': False,
            },
            bases=('compound.basecompound',),
        ),
    ]
