# Generated by Django 3.0.3 on 2020-07-22 17:51

import chemreg.common.validators
import chemreg.compound.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0002_iris_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illdefinedcompound',
            name='query_structure_type',
            field=models.ForeignKey(default=chemreg.compound.models.get_illdefined_qst, on_delete=django.db.models.deletion.PROTECT, to='compound.QueryStructureType', validators=[chemreg.common.validators.validate_deprecated]),
        ),
    ]
