# Generated by Django 3.0.3 on 2020-05-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compound", "0002_alter_cid_inchikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecompound",
            name="qc_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="basecompound",
            name="replaced_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaces",
                to="compound.BaseCompound",
            ),
        ),
    ]
