# Generated by Django 3.0.3 on 2020-05-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compound", "0003_soft_delete_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basecompound",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="definedcompound",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="querystructuretype",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
