# Generated by Django 3.0.3 on 2020-03-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0003_query_structure_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllDefinedCompound',
            fields=[
                ('basecompound_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compound.BaseCompound')),
                ('query_structure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compound.QueryStructureType')),
            ],
            options={
                'abstract': False,
            },
            bases=('compound.basecompound',),
        ),
    ]
