# Generated by Django 3.0.3 on 2020-08-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0003_mago_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecompound',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='definedcompound',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='illdefinedcompound',
            options={'base_manager_name': 'objects', 'verbose_name': 'ill-defined compound'},
        ),
        migrations.AlterModelOptions(
            name='querystructuretype',
            options={'ordering': ['pk']},
        ),
    ]
