# Generated by Django 3.0.3 on 2020-06-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0003_inherit_controlled_vocabulary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definedcompound',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='basecompound',
            name='qc_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='basecompound',
            name='replaced_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='compound.BaseCompound'),
        ),
    ]
