# Generated by Django 3.0.3 on 2020-10-28 14:18

import chemreg.compound.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0004_orion_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecompound',
            name='id',
        ),
        migrations.AlterField(
            model_name='basecompound',
            name='cid',
            field=models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
