# Generated by Django 3.0.3 on 2020-03-17 20:19

import chemreg.compound.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0004_illdefinedcompound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecompound',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='illdefinedcompound',
            options={'verbose_name': 'ill-defined compound'},
        ),
        migrations.AlterField(
            model_name='illdefinedcompound',
            name='query_structure_type',
            field=models.ForeignKey(default=chemreg.compound.models.get_illdefined_qst, on_delete=django.db.models.deletion.PROTECT, to='compound.QueryStructureType'),
        ),
    ]
