# Generated by Django 3.0.3 on 2020-03-18 20:54

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compound", "0005_illdefinedcompoundquerystructuretype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definedcompound",
            name="inchikey",
            field=computed_property.fields.ComputedCharField(
                compute_from="_inchikey", editable=False, max_length=29
            ),
        ),
    ]
