# Generated by Django 3.0.3 on 2020-03-20 19:15

import chemreg.compound.utils
import chemreg.compound.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compound", "0006_computed_inchikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecompound",
            name="cid",
            field=models.CharField(
                default=chemreg.compound.utils.build_cid,
                max_length=50,
                unique=True,
                validators=[
                    chemreg.compound.validators.validate_cid_regex,
                    chemreg.compound.validators.validate_cid_checksum,
                ],
            ),
        ),
    ]
