# Generated by Django 3.0.3 on 2020-03-20 20:37

import chemreg.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compound", "0007_rm_cid_prefix_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecompound",
            name="created_by",
            field=models.ForeignKey(
                default=chemreg.common.utils.get_current_user_pk,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basecompound_created_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="basecompound",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basecompound_updated_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="querystructuretype",
            name="created_by",
            field=models.ForeignKey(
                default=chemreg.common.utils.get_current_user_pk,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="querystructuretype_created_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="querystructuretype",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="querystructuretype_updated_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
