# Generated by Django 3.0.3 on 2020-08-13 17:08

import chemreg.common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_mago_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='long_description',
            field=chemreg.common.models.HTMLTextField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='short_description',
            field=chemreg.common.models.HTMLTextField(max_length=1000),
        ),
    ]
