# Generated by Django 3.0.3 on 2020-08-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_nash_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilitytype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='externalcontact',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='identifiertype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='listtype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='recordidentifier',
            options={'ordering': ['pk']},
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('external_id', 'list'), name='unique_external_id'),
        ),
    ]
