# Generated by Django 3.0.3 on 2020-06-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'objects', 'ordering': ['pk']},
        ),
    ]
