# Generated by Django 3.0.3 on 2020-08-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_iris_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
    ]
