# Generated by Django 3.0.3 on 2020-03-20 20:37

import chemreg.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                default=chemreg.common.utils.get_current_user_pk,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_created_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_updated_by_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
