# Generated by Django 3.0.3 on 2020-06-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_substancetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source", options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="substancetype",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
    ]
