# Generated by Django 3.0.3 on 2020-06-17 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chemreg.common.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("substance", "0001_iris_sprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="SynonymType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(max_length=49, unique=True)),
                ("label", models.CharField(max_length=99, unique=True)),
                ("short_description", models.CharField(max_length=499)),
                ("long_description", models.TextField()),
                ("deprecated", models.BooleanField(default=False)),
                ("validation_regular_expression", models.TextField(blank=True)),
                ("score_modifier", models.FloatField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=chemreg.common.utils.get_current_user_pk,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synonymtype_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synonymtype_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
    ]
