# Generated by Django 3.0.3 on 2020-12-09 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0001_vega_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='display_name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 =<>\\-\\*_':.,^%&\\/{}[\\]?()+]{3,}$", message="The proposed display name does not conform to the regular expression ^[a-zA-Z0-9 =<>\\-\\*_':.,^%&\\/{}[\\]?()+]{3,}$")]),
        ),
        migrations.AlterField(
            model_name='substance',
            name='preferred_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 =<>\\-\\*_':.,^%&\\/{}[\\]?()+]{3,}$", message="The proposed Preferred Name does not conform to the regular expression ^[a-zA-Z0-9 =<>\\-\\*_':.,^%&\\/{}[\\]?()+]{3,}$")]),
        ),
    ]
