# Generated by Django 3.0.3 on 2020-08-12 16:02

import chemreg.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0005_mago_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymtype',
            name='is_casrn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substance',
            name='casrn',
            field=models.CharField(max_length=50, unique=True,
                                   validators=[chemreg.common.validators.validate_casrn_format,
                                               chemreg.common.validators.validate_casrn_checksum]),
        ),
        migrations.AlterField(
            model_name='synonymtype',
            name='validation_regular_expression',
            field=models.TextField(blank=True, validators=[chemreg.common.validators.validate_is_regex]),
        ),
    ]
