# Generated by Django 3.0.3 on 2020-08-20 17:54

import chemreg.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0005_mago_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymtype',
            name='is_casrn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substance',
            name='casrn',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2,7}-[0-9]{2}-[0-9]$', message='The proposed CASRN does not conform to the regular expression ^[0-9]{2,7}-[0-9]{2}-[0-9]$'), chemreg.common.validators.validate_casrn_checksum]),
        ),
        migrations.AlterField(
            model_name='substance',
            name='display_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$', message='The proposed display name does not conform to the regular expression ^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='substance',
            name='preferred_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$', message='The proposed Preferred Name does not conform to the regular expression ^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='synonymtype',
            name='validation_regular_expression',
            field=models.TextField(blank=True, validators=[chemreg.common.validators.validate_is_regex]),
        ),
    ]
