# Generated by Django 3.0.3 on 2020-08-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0004_orion_sprint'),
        ('substance', '0006_nash_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qclevelstype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='substance',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='substancetype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonymquality',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonymtype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='substance',
            name='associated_compound',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substance', to='compound.BaseCompound'),
        ),
    ]
