# Generated by Django 3.0.3 on 2020-08-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0006_nash_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qclevelstype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='substance',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='substancetype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonymquality',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='synonymtype',
            options={'ordering': ['pk']},
        ),
    ]
