# Generated by Django 3.0.3 on 2020-10-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0007_orion_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='display_name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$', message='The proposed display name does not conform to the regular expression ^[a-zA-Z0-9 =<>\\-:.,^%&/{}[\\]()+?=]{3,}$')]),
        ),
    ]
