# Generated by Django 3.0.3 on 2020-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0007_orion_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='substance',
            name='private_qc_note',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='substance',
            name='public_qc_note',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
